
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp arrSum.cpp fillArr.cpp reverse.cpp triAnglular.cpp menu.cpp getInput.cpp
HEADERS = Ant.hpp arrSum.hpp fillArr.hpp reverse.hpp triAnglular.hpp  menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o simpleProgram

clean:
	rm simpleProgram
