
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp queueNode.cpp menu.cpp getInput.cpp
HEADERS = queueNode.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o queList
clean:
	rm queList
