
CXX = g++
CXXFLAGS = -std=c++11

SRCS = main.cpp zoo.cpp animal.cpp tiger.cpp penguin.cpp turtle.cpp menu.cpp getInput.cpp
HEADERS = zoo.hpp animal.hpp tiger.hpp penguin.hpp turtle.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o zootycoon
clean:
	rm zootycoon
