
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = Arena.cpp Tournament.cpp fantasyCG.cpp Vampire.cpp Barbarian.cpp Bluemen.cpp Medusa.cpp Harry.cpp menu.cpp getInput.cpp
HEADERS = Tournament.hpp fantasyCG.hpp Vampire.hpp Barbarian.hpp Bluemen.hpp Medusa.hpp Harry.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o fantasyT
clean:
	rm fantasyT
