
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main2.cpp simpleSearch.cpp readFile.cpp sortOut.cpp biSearch.cpp getInput.cpp
HEADERS = simpleSearch.hpp readFile.hpp sortOut.cpp biSearch.cpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o searchTest
clean:
	rm searchTest
