
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp fantasyCG.cpp Vampire.cpp Barbarian.cpp Bluemen.cpp Medusa.cpp Harry.cpp Game.cpp menu.cpp getInput.cpp
HEADERS = fantasyCG.hpp Vampire.hpp Barbarian.hpp Bluemen.hpp Medusa.hpp Harry.hpp Game.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o fantasy
clean:
	rm fantasy
