
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp doublyList.cpp menu.cpp getInput.cpp
HEADERS = doublyList.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o linkedList
clean:
	rm linkedList
