
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp game.cpp loadedDie.cpp die.cpp menu.cpp getInput.cpp
HEADERS = game.hpp loadedDie.hpp die.hpp menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o dicewar
clean:
	rm dicewar
