
CXX = g++
CXXFLAGS = -std=c++0x

SRCS = main.cpp university.cpp building.cpp person.cpp  instructor.cpp student.cpp menu.cpp getInput.cpp
HEADERS = university.hpp building.hpp person.hpp instructor.hpp student.hpp  menu.hpp getInput.hpp

antp: ${SRCS} ${HEADER}
	${CXX} ${CXXFLAGS} ${SRCS} -o osuinfo
clean:
	rm osuinfo
